### ISSUE TITLE
Remove the code changes to load config.properties from Tomcat in REMReM-Publish

### ISSUE THREAD

**Issue by zburswa** [eiffel-community/eiffel-remrem-publish#158]
Based on the analysis done for the application, it is observed that when the  Publish application is run externally from tomcat, instead of loading the properties from conf/config.properties, remrem is looking for application.properties in src/main/resources/application.properties and loading these properties in war file.

Currently we are overriding these application properties with the config.properties.

But we can set the external configurations via environmental variables in setenv file in tomcat and when the application is started, these configurations will be loaded as application.properties.

So, the code which was written to load the properties from conf folder can be removed.

**Comment by SantoshNC68** [comment]
@zburswa  is this bug still valid? Can we close the issue?

**Comment by zburswa** [comment]
This issue is resolved as part of the pull request #160 . We can close this issue.
