### ISSUE TITLE
/generateAndPublish does not give 400 response when trying to publish invalid Eiffel events

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel-remrem-publish#169]
### Description
When using the /generateAndPublish endpoint in REMReM publish with invalid Eiffel event the response returns HTTP status code 500 and Internal server error. But if I would try and validate the exact same invalid Eiffel event using REMReM generate service the response returned gives HTTP status code 400 and more information about what exactly is wrong in the Eiffel event.  The REMReM publish service /generateAndPublish endpoint does not give any valuable information back to user if they try to publish an invalid Eiffel event.

### Motivation
The user understands what went wrong with the request towards REMReM publish, without having to go through the logs or go to REMReM generate service to double check with templates of Eiffel events and try to figure out what is invalid JSON.

### Exemplification
When a user tries to publish an Eiffel event using /generateAndPublish endpoint with invalid Eiffel event, I would like the REMReM publish service to forward the response from REMReM generate back to the user. 

User documentation about the REST API needs to be updated to relfect the changes.

### Benefits
Easier to use REMReM publish /generateAndPublish endpoint.

### Possible Drawbacks
None.

**Comment by zburswa** [comment]
The changes for the issue are done and raised the pullrequest.
Url for Pull Request: https://github.com/eiffel-community/eiffel-remrem-publish/pull/173

**Comment by SantoshNC68** [comment]
Code changes are merged for this issue, 2.0.9 release has this fix. 
Closing the issue.
