### ISSUE TITLE
A too long domainId gives faulty error message

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/eiffel-remrem-publish#172]
### Description
The /producer/msg and /generateAndPublish entrypoints return a misleading error message when the given domainId in a message is too long.
The maximum length of a routing key in RabbitMQ is 255 characters. The routing key is built up by REMReM by adding event family and type to the domainId. If the domainId is long the routing key can therefore be more than 255 characters.
When trying to send a message with such a long domain id towards /producer/msg or /generateAndPublish the error message returned is:
{
  "events": [
    {
      "id": "23b92cd0-b741-49e8-80e5-313d6d4bcfed",
      "status_code": 500,
      "result": "Internal Server Error",
      "message": "RabbitMQ is down. Please try later"
    }
  ]
}
That message should be corrected. And the status_code should probably be 400 instead.

### Motivation
It gives the user a faulty impression about the MB being down, while it is actually a fault in the input message.

### Exemplification
EiffelArtifactCreatedEvent:
{
  "msgParams": {
    "meta": { 
      "source": {
        "domainId": "eiffel912.seki.test123.extrastuff.withaverylongtail123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890",
        "name": "Bobs CI machine"
      }
    }
  },
  "eventParams": {
    "data": {
      "identity": "pkg:my/test/identity" 
    }
  }
}

### Benefits
Better error reporting

### Possible Drawbacks
None

**Comment by SantoshNC68** [comment]
Yes agree, there is a limitation about routing key in RabbitMQ and we should document it.

**Comment by e-backmark-ericsson** [comment]
> Yes agree, there is a limitation about routing key in RabbitMQ and we should document it.

It should not just be documented, but also the response to the user should be more to the point. It should be a client error (for example 400) instead of internal server error.
