### ISSUE TITLE
The virtualhost used for RabbitMQ connections must be configurable

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-remrem-publish#175]
### Description
There is no configuration option for which RabbitMQ virtualhost to connect to. Connections will always be made to the default virtualhost, "/". Just like we can configure the hostname, port, use of TLS, username, and password we should be able to configure the virtualhost.

### Motivation
Virtualhosts are frequently used for multi-tenancy or to separate production environments and  test environments. Any RabbitMQ client should be able to connect to any available virtualhost.

**Comment by magnusbaeck** [comment]
With the merging of #196 this issue is done and can be closed, right?

**Comment by m-linner-ericsson** [comment]
@magnusbaeck You can close this if you are satisfied with the solution
