### ISSUE TITLE
Service should not die if RabbitMQ is unavailable when starting up

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-remrem-publish#179]
### Description
If the RabbitMQ server is unavailable (or the connection fails for some other reason, e.g. an authentication problem) when the application starts up the initialization fails and everything dies. If running under Tomcat the REST endpoints will remain unregistered and return 404 errors. Instead, RabbitMQ connections should be set up lazily outside of the initialization.

### Motivation
A network partition or other unavailability of an external service must never cause this service to end up in an unrecoverable state that requires manual intervention. Errors can either be returned to the caller (where applicable) or a retry loop can block the caller for some time (possibly forever).

### Benefits
A more fault tolerant service that requires less operational support.

### Possible Drawbacks
None I can think of.

**Comment by SantoshNC68** [comment]
If the RabbitMQ is down if the publish service is up and running, it will fail to send the messages even after retry. To make sure that we have problems connecting to RabbitMQ it is good to stop, when the RabbitMQ is up you can start the service.
 But if the RabbitMQ goes down when the service is running you will get appropriate messages.

It is good to not loose any messages even when starting the service.

**Comment by magnusbaeck** [comment]
We should of course never lose messages, but refusing to start because RabbitMQ is unavailable doesn't improve reliability in _any_ way. With the current behavior it's actually quite the opposite; if the Publish app is down and Tomcat responds with 404 it's the same status code as if the client sends a request to publish to a message protocol that hasn't been configured (https://eiffel-community.github.io/eiffel-remrem-publish/statusCodes.html).

Furthermore, having an application that responds to downstream outages in different ways depending on when the downstream service failed is inconsistent and weird. It'll even respond in different ways depending on the deployment method (Tomcat or similar application server or standalone).

**Comment by SantoshNC68** [comment]
Perhaps, but consider the below example:
I have a jenkins job sending 100s of events through Remrem, if we start the publish service without checking if the MB is up and running there is high possibility that we would end up failing to see those events.
Instead when you try to stop the Publish service saying that the MB is configured incorrectly or is not up and running will give you clear understanding before the Publish service is up. So we just either reconfigure proper properties or restart MB so that the Publish service will be up and running.


In the above scenario, if we start the publish and provide retries until it dies or for certain amount of time we will loose the messages without storing any information(if retries fail). just because of some issues with MB it should never fail.

But when the tomcat is down for service, it won't respond with 404 status code, it will be one of 5XX  (if that is an issue may be we need to create an issue for that)

So with the current implementation we try to provide a chance for a person who starts the Publish to check if everything is configured correctly or not and if not then provide the correct values before starting again. This is much clearer in my opinion.

**Comment by magnusbaeck** [comment]
> I have a jenkins job sending 100s of events through Remrem, if we start the publish service without checking if the MB is up and running there is high possibility that we would end up failing to see those events.

Why would that happen? RabbitMQ can fail at _any_ time, and regardless of when it fails REMReM Publish should respond consistently and correctly. Since we're dealing with synchronous HTTP calls that time out after a relatively short time we can't just retry forever since the client will disconnect after maybe 30 or 60 seconds. What we can do is either fail immediately or retry for a limited amount of time (<30 seconds) and then fail. See https://github.com/eiffel-community/eiffel-remrem-generate/issues/152 for a discussion about what REMReM Generate does when the ER is unavailable. It's the exact same problem.

REMReM Clients _must_ be prepared for failure and either have a retry loop on their side or accept that events get dropped.

> But when the tomcat is down for service, it won't respond with 404 status code, it will be one of 5XX (if that is an issue may be we need to create an issue for that)

Not when the whole Tomcat instance is down, no, but if the Publish app fails to initialize Tomcat will still be running but since the app isn't up its endpoints won't be bound to anything and you therefore get a 404.

> So with the current implementation we try to provide a chance for a person who starts the Publish to check if everything is configured correctly or not and if not then provide the correct values before starting again. This is much clearer in my opinion.

It seems you're making a couple of assumptions:

* The Publish service is always started by a human.
* RabbitMQ connection problems are only caused by configuration mistakes.

Neither of these assumptions are correct. I would agree that it makes sense to abort the startup if the configuration has severe problem (missing configuration values, obviously bad syntax etc) that prevents us from continuing, but not being able to set up a connection to a service we depend on isn't necessarily a configuration problem.

I don't mind REMReM Publish performing some kind of diagnostic check to see if it's able to set up a channel (in fact, it probably should so we can set up a /health endpoint that monitoring tools can probe), but a failure must not stop the application for the reasons I've explained.

**Comment by magnusbaeck** [comment]
@SantoshNC68, could we conclude this discussion?

**Comment by SantoshNC68** [comment]
Well, I haven't looked onto it, after the discussion. But will try to read and check this. Will comment after checking the possibilities.

**Comment by erjamni-raja** [comment]
Hello Magnus, thanks for the contribution to this issue. 
I do agree with you that **_REMReM Publish should not die if RabbitMq is unavailable._**
But my view is, with this feature we have pros and cons.
### Pros:

- REMReM Publish will connect when Rabbit MQ up.
- REMReM publish can connect with multiple RabbitMQ's (each protocol connect with a RabbitMQ)
ex:
`[
   {
      "mp":"eiffelsemantics",
      "host":"127.0.0.1",
      "port":"5672",
      "username":"guest",
      "password":"guest",
      "tls":"",
      "exchangeName":"amq.direct",
      "domainId":"eiffelxxx",
      "createExchangeIfNotExisting":true
   },
   \   {
      "mp":"xxxxx",
      "host":"127.0.0.1",
      "port":"5672",
      "username":"guest",
      "password":"guest",
      "tls":"",
      "exchangeName":"amq.direct",
      "domainId":"eiffelxxx",
      "createExchangeIfNotExisting":true
   }
]`
if one RabbitMQ is available and another is **unavailable**, REMReM publish will work for **available** RabbitMQ.

### Cons

- REMReM publish we have only 3 endpoints, 2 endpoints are depended on RabbitMQ. So without Rabbit MQ connection, there is no other use from service.
- Rabbit MQ connection, it is hard to find **is service down or configurations are wrong**. If by any chance user enters the wrong configuration, the user will wait and after some time he realizes configurations are wrong.

Let's see other's views on this issue, then we can conclude.

**Comment by magnusbaeck** [comment]
> REMReM publish we have only 3 endpoints, 2 endpoints are depended on RabbitMQ. So without Rabbit MQ connection, there is no other use from service.

Of course. The point of REMReM Publish is to publish messages to RabbitMQ so if the broker is unavailable this application will also effectively be unavailable, but that's not a reason to refuse to start if the broker is down.

**Comment by SantoshNC68** [comment]
After going through this item, I agree to the comments made by Magnus B.

**Comment by m-linner-ericsson** [comment]
Was fixed by https://github.com/eiffel-community/eiffel-remrem-publish/pull/248
