### ISSUE TITLE
How to create multiple listnerAdapter with the same queue

### ISSUE THREAD

**Issue by KOSSOKO** [eiffel-community/eiffel-remrem-publish#181]
Hi, first of all, thanks for the project very well explained and a clear code.

I'm developing my own asynchronous service based on your source code.

You have in the AMQPConfig declared 
```
	SimpleMessageListenerContainer container(ConnectionFactory connectionFactory,
			MessageListenerAdapter listenerAdapter) {
		SimpleMessageListenerContainer container = new SimpleMessageListenerContainer();
		container.setConnectionFactory(connectionFactory);
		container.setQueueNames(rabbitMQProperties.getQueueName());
		container.setMessageListener(listenerAdapter);
		return container;
	}
```

Then 
```
    @Bean
    MessageListenerAdapter listenerAdapter(DeveloperTransactionListener devListner) {
        return new MessageListenerAdapter(devListner, "devCashout");
    }
}
```
My question 
I wanted to add another listner to redirect to another method in my class DeveloperTransactionListener  without creating another queue. How could I achieve this ? 

Thanks in advance.

**Comment by Christoffer-Cortes** [comment]
I'm not super familiar with the code in remrem-publish but I don't think publish consumes any messages, so I don't think either of the code snippets you posted is part of this component. I am also not super familiar with springs amqp classes but I'm just assuming that listener means a consumer. If that is true, are you sure you really want two consumers on the same queue directing to different methods? Consumers will take turns removing items from a queue, so if a consumer takes a message that was meant for the other "method" then that message is lost. If you want both consumers to receive the message you need to set up two queues with a consumer each.

**Comment by SantoshNC68** [comment]
@KOSSOKO since this is not something in the Eiffel code for publish, I suggest you to verify if this issue to be created in other repositories? I will close the issue.
