### ISSUE TITLE
Remove example configuration for tests

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel-remrem-publish#192]
### Description
https://github.com/eiffel-community/eiffel-remrem-publish/blob/master/wiki/markdown/usage/service.md and https://github.com/eiffel-community/eiffel-remrem-publish/blob/master/publish-service/src/main/resources/application.properties contains Ericsson specific examples of RabbitMQ configuration used for tests. 

### Motivation
These examples should be removed the GitHub repository.

### Exemplification
Any mention of Ericsson specific RabbitMQ hosts should be removed. The mention of eiffel3 protocol should be removed. The only supported protocol is named "eiffelsemantics" and this should be clarified in the documentation. It can be replaced with a more generic protocol name so users can copy + paste their own protocols into the configuration.

### Benefits
Keeping the documentation fit for a wider range of users will make it more understandable.

### Possible Drawbacks
None.

**Comment by SantoshNC68** [comment]
@e-pettersson-ericsson this has been resolved and we are closing the issue.
