### ISSUE TITLE
CHANGELOG is not readable

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel-remrem-publish#193]
### Description
The CHANGELOG contains some weird formatting, making it impossible to read. From what I can see it has not been updated in 2 years so should it be kept or removed? If it should be kept, the file type should change (remove the .swp) and the formatting should be corrected so it is possible to read.

https://github.com/eiffel-community/eiffel-remrem-publish/blob/master/.CHANGELOG.md.swp

### Motivation
A changelog should be readable (and up to date)

### Benefits
A readable CHANGELOG 

### Possible Drawbacks
None that I can think of.

**Comment by magnusbaeck** [comment]
.CHANGELOG.md.swp is a temporary file created by vim that should never have been committed in the first place.

```plain
$ file .CHANGELOG.md.swp
.CHANGELOG.md.swp: Vim swap file, version 8.0, pid 7472, user ezsahoi, host SE00215708, file ~ezsahoi/git/eiffel-remrem-publish/CHANGELOG.md, modified
```

I'll send a PR to remove it. The actual changelog in CHANGELOG.md appears to be well-maintained.
