### ISSUE TITLE
/producer/msg should return status code 400 instead of 500 when the given body is not a JSON object

### ISSUE THREAD

**Issue by Isacholm** [eiffel-community/eiffel-remrem-publish#201]
### Description
When sending something else than a JSON-object as body returns the status code 500. Since the issue lies with the user it should be return to the user that the body is of the wrong type (400) not that the server is broken.

### Motivation
This seems like a common exception and should be handled.
Status code 400 with a clear message that helps the user when sending something invalid instead of telling the user that the server is broken.

### Benefits
A clear API response helps the user.
API maintainers can focus on fixing real issues.

### Possible Drawbacks
The API-documentation for status code 400 suggests that this status code is only returned when there is something wrong with the event **content** (Invalid event content), This can't be known if the content couldn't even be read because of a bad datatype.

**Comment by z-sztrom** [comment]
Probably solved by a former update. All requests response correctly with status 400 when a non-JSON body is provided

```
{
  "timestamp": "Apr 6, 2023 12:31:35 PM",
  "status": 400,
  "error": "Bad Request",
  "path": "/eiffelsemantics"
}
```

Checked endpoints accepting event body on both publish and generate service.
