### ISSUE TITLE
Fix minor documentation issues and deprecate GitHub pages

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-remrem-publish#213]
### Description
During 2020 the GitHub Pages contents was migrated to regular Markdown pages on the master branch, but:
* The first paragraph of README.md still links to the GitHub Pages site.
* The formatting of some of the Markdown pages is poor, see e.g. the JSON example in the [service usage page](https://github.com/eiffel-community/eiffel-remrem-publish/blob/master/wiki/markdown/usage/service.md#usage).

Suggested actions:
* Remove any remaining references to GitHub Pages.
* Replace the contents of the GitHub Pages pages with links to the current documentation.
* Fix formatting issues and any other minor problems encountered while proof-reading.

### Motivation
We should obviously not link to outdated documentation and the available documentation should be formatted for legibility.

### Exemplification
I myself had forgotten about the documentation migration and accidentally followed the first documentation link in the README file and ended up in the old documentation, which I then linked to in our organization's internal documentation.

### Benefits
Easier for users to find up to date documentation.

### Possible Drawbacks
None.

**Comment by z-sztrom** [comment]
Hi @magnusbaeck, 

you wrote: "The first paragraph of README.md still links to the GitHub Pages site.". What should be used as a replacement?

**Comment by m-linner-ericsson** [comment]
When removing the link also remove the `gh-pages` branch not to let GitHub generate those pages

**Comment by magnusbaeck** [comment]
Sorry for dropping this ball.

> you wrote: "The first paragraph of README.md still links to the GitHub Pages site.". What should be used as a replacement?

Can't we just remove that sentence? The documentation table of contents is further down in the file.

**Comment by z-sztrom** [comment]
Branch `gh-pages` deleted.
