### ISSUE TITLE
Dockerized service fails to start as of 2.0.29

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-remrem-publish#271]
### Description
I've built a Docker image from 2.0.29 and tried to run it with the same configuration as I've used earlier, but the startup fails with the following exception:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'documentationPluginsBootstrapper' defined in URL [jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/springfox-spring-web-2.6.1.jar!/springfox/documentation/spring/web/plugins/DocumentationPluginsBootstrapper.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webMvcRequestHandlerProvider' defined in URL [jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/springfox-spring-web-2.6.1.jar!/springfox/documentation/spring/web/plugins/WebMvcRequestHandlerProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Invalid mapping on handler class [com.ericsson.eiffel.remrem.publish.controller.ProducerController]: public org.springframework.http.ResponseEntity com.ericsson.eiffel.remrem.publish.controller.ProducerController.send(java.lang.String,java.lang.String,java.lang.String,java.lang.String,com.google.gson.JsonElement)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.23.jar:5.3.23]
...
```

Full startup log: [publish-2.0.29-startup.log](https://github.com/eiffel-community/eiffel-remrem-publish/files/11869326/publish-2.0.29-startup.log)

The same configuration and build procedure works with 2.0.28. The application.properties file looks like this (with redactions):

```
debug: true
rabbitmq.instances.jsonlist: [{"mp": "eiffelsemantics", "host": "rabbitmq.example.com", "port": 5671, "username": "REDACTED", "password": "REDACTED", "tls": "default", "virtualHost": "sandbox", "exchangeName": "eiffel.public", "domainId": "example", "createExchangeIfNotExisting": false}]
generate.server.uri: https://eiffel-remrem-generate-prod.example.com
generate.server.contextpath: /
```

### Motivation
Deployment of the service as a Docker container should be supported.

### Exemplification
N/A

### Benefits
Working Docker image.

### Possible Drawbacks
None.

**Comment by z-sztrom** [comment]
I've build Docker image for 2.1.1 according to instructions available at https://github.com/eiffel-community/eiffel-remrem-publish/blob/master/wiki/markdown/docker.md. The built image started up successfully without an issue.

The reported issue is/was probably an issue related to release 2.0.29.

I suggest to close the issue.

**Comment by m-linner-ericsson** [comment]
@magnusbaeck Do you agree?

**Comment by magnusbaeck** [comment]
I can verify this later today or tomorrow. But feel free to close the issue. We an always reopen if the problem persists.

**Comment by m-linner-ericsson** [comment]
Closing as per discussion.

**Comment by magnusbaeck** [comment]
> I've build Docker image for 2.1.1 according to instructions available at https://github.com/eiffel-community/eiffel-remrem-publish/blob/master/wiki/markdown/docker.md. The built image started up successfully without an issue.

I'm still having issues getting a working container. I believe I did what you did and the container did start up, but all requests fail with a 404 error. There's nothing interesting in the logs. Should I create a new issue or you do you want handle this?

**Comment by m-linner-ericsson** [comment]
If you think the description is still valid the issue can be reopened otherwise a new one should be opened.

**Comment by magnusbaeck** [comment]
Yeah, sorry for not following up. It was a mistake on my part. After an hour of debugging and drafting a really nice GitHub issue I realized I'd use the wrong dockerfile.

**Comment by z-sztrom** [comment]
No problem, it happens. So, we can close the ticket, right?

**Comment by magnusbaeck** [comment]
It's already closed :-)
